---
swagger: "2.0"
info:
  description: "API description in Markdown."
  version: "1.0.0"
  title: "Sample API"
host: "api.example.com"
basePath: "/v1"
schemes:
- "https"
paths:
  /users:
    get:
      summary: "Returns a list of users."
      operationId: "usersGET"
      parameters: []
      responses:
        "200":
          description: "A list of users."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
      x-swagger-router-controller: "Default"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    example:
      name: "name"
      id: 0
